trigger:
  branches:
    include:
      - develop
      - staging
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: sfeauto

steps:

- script: |
    echo "Deploying branch: $(Build.SourceBranchName)"

    if [ "$(Build.SourceBranchName)" = "main" ]; then
      vercel deploy --prod \
        --token=$(VERCEL_TOKEN) \
        --yes \
        --meta gitBranch=$(Build.SourceBranchName)
    else
      vercel deploy \
        --token=$(VERCEL_TOKEN) \
        --yes \
        --meta gitBranch=$(Build.SourceBranchName)
    fi
  displayName: "Deploy to Vercel"