-- AlterTable
ALTER TABLE `intervention_int` MODIFY `int_status` ENUM('WAITING_FOR_PARTS', 'FIXING_STARTED', 'FIXING_FINISHED', 'WAITING_FOR_APPROVAL', 'REFUSED', 'CANCELLED', 'DELETED') NOT NULL DEFAULT 'FIXING_STARTED';

-- AlterTable
ALTER TABLE `statushistory_sth` MODIFY `sth_previousStatus` ENUM('WAITING_FOR_PARTS', 'FIXING_STARTED', 'FIXING_FINISHED', 'WAITING_FOR_APPROVAL', 'REFUSED', 'CANCELLED', 'DELETED') NOT NULL,
    MODIFY `sth_newStatus` ENUM('WAITING_FOR_PARTS', 'FIXING_STARTED', 'FIXING_FINISHED', 'WAITING_FOR_APPROVAL', 'REFUSED', 'CANCELLED', 'DELETED') NOT NULL;
